remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Luu Family Network
description: The private domain of the Luu family.
show_downloads: false
